; Script generated by the pharmML2Nmtran Converter v.0.4.0
; Source 	: PharmML 0.8.1
; Target 	: NMTRAN 7.3.0
; Model 	: Samtani_2010_steady_state_diabetes
; Model Name: Generated from MDL. MOG ID: Method_1_Samtani_mog
; Dated 	: Fri Sep 02 17:54:45 CEST 2016

$PROBLEM Generated from MDL. MOG ID: Method_1_Samtani_mog

$INPUT  ID TIME DV FPG EV=DROP
$DATA "Simulated_Samtani_2010_ss_data.csv" IGNORE=@

$PRED 
BETA0 = THETA(1)
BETA1 = THETA(2)
RES = THETA(3)



HBA1C = (BETA0+(BETA1*FPG))

EPS_1 = EPS(1)

IPRED = HBA1C
W = RES
Y = IPRED+W*EPS_1
IRES = DV - IPRED
IWRES = IRES/W

$THETA 
(2.84 )	;BETA0
(0.5 )	;BETA1
(0.0  FIX )	;RES

$OMEGA 0 FIX

$SIGMA 
1.0 FIX


$EST METHOD=COND NSIG=3 SIGL=9 MAXEVALS=9999 PRINT=10 NOABORT

$TABLE  ID TIME FPG PRED RES WRES DV IPRED IRES IWRES Y NOAPPEND NOPRINT FILE=sdtab

$TABLE  ID FPG NOAPPEND NOPRINT FILE=cotab


